### ISSUE TITLE
Can't open Tasks, Procedures and Functions panes

### ISSUE THREAD

**Issue by kristiank** [GIRA/UziScript#10] opened 2019-12-05 15:23 UTC
When running Physical BITS from the master branch I get the following error messages when clicking on the Tasks, Procedures and Functions panes. The panes don't open and remains "highlighted". The other panes works fine. When running the 0.2.1 release, then the Tasks pane works.

```javascript
uncaught exception: undefined
es
ide.js:623:7
Will-change memory consumption is too high. Budget limit is the document surface area multiplied by 3 (906528 px). Occurrences of will-change over the budget will be ignored.
index.html

// clicking on Tareas pane
TypeError: blocks.map(...).flat is not a function[Learn More]
blocks.js:95:24
init/</<
http://localhost:8080/web/ide/blocks.js:95:24
Blockly.Flyout.prototype.show
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:1456:312
Blockly.Toolbox.TreeControl.prototype.setSelectedItem
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:1499:410
goog.ui.tree.BaseNode.prototype.select
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:831:235
Blockly.Toolbox.TreeNode.prototype.onMouseDown
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:1501:299
goog.ui.tree.TreeControl.prototype.handleMouseEvent_
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:889:208
goog.events.fireListener
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:184:124
goog.events.handleBrowserEvent_
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:187:230
goog.events.getProxy/b<
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:176:141

// clicking on Procedimientos pane
TypeError: blocks.map(...).flat is not a function[Learn More]
blocks.js:203:24
init/</<
http://localhost:8080/web/ide/blocks.js:203:24
Blockly.Flyout.prototype.show
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:1456:312
Blockly.Toolbox.TreeControl.prototype.setSelectedItem
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:1499:410
goog.ui.tree.BaseNode.prototype.select
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:831:235
Blockly.Toolbox.TreeNode.prototype.onMouseDown
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:1501:299
goog.ui.tree.TreeControl.prototype.handleMouseEvent_
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:889:208
goog.events.fireListener
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:184:124
goog.events.handleBrowserEvent_
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:187:230
goog.events.getProxy/b<
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:176:141

// clicking on Funciones pane
TypeError: blocks.map(...).flat is not a function[Learn More]
blocks.js:254:24
init/</<
http://localhost:8080/web/ide/blocks.js:254:24
Blockly.Flyout.prototype.show
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:1456:312
Blockly.Toolbox.TreeControl.prototype.setSelectedItem
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:1499:410
goog.ui.tree.BaseNode.prototype.select
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:831:235
Blockly.Toolbox.TreeNode.prototype.onMouseDown
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:1501:299
goog.ui.tree.TreeControl.prototype.handleMouseEvent_
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:889:208
goog.events.fireListener
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:184:124
goog.events.handleBrowserEvent_
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:187:230
goog.events.getProxy/b<
http://localhost:8080/web/ide/libs/google-blockly/blockly_compressed.js:176:141
```

**Comment by RichoM** [comment] 2019-12-05 16:05
Man, I hate javascript... From looking at the stack trace it seems to be a browser compatibility issue. It could probably be fixed by providing a polyfill for the flat() function.

**Comment by kristiank** [comment] 2019-12-05 18:11
I'll try dive into this while waiting for your thoughts on the block building part.

**Comment by kristiank** [comment] 2019-12-06 07:35
Found one polyfill on [stackoverflow](https://stackoverflow.com/questions/50993498/flat-is-not-a-function-whats-wrong). I'll post it here as a note for myself and try it next time I have time, probably monday morning.

**Comment by RichoM** [comment] 2019-12-06 15:56
Thank you, I added the polyfill. Unfortunately I couldn't reproduce the bug in any of the browsers I have in my computer so I couldn't test this. Would you confirm it fixes the problem?

**Comment by kristiank** [comment] 2019-12-07 08:57
It works on my Firefox 60.9.0esr. Great!

**Closed** 2019-12-09 22:26 UTC
